language: c

before_install:
  - git submodule update --init --recursive

install:
    - sudo apt-get update > /dev/null
    - sudo apt-get build-dep smuxi > /dev/null
    - sudo apt-get install mono-devel nunit-console moreutils gtk-sharp2-gapi libgtkspell-dev > /dev/null

script:
    - ./autogen.sh MCS=/usr/bin/dmcs
    - find lib/ -name "*.csproj" -exec sed 's!<WarningLevel>[0-9]</WarningLevel>!<WarningLevel>0</WarningLevel>!' -i {} \;
    - xbuild /p:Warn=0 src/smuxi.sln
    - nunit-console bin/release/smuxi-common-tests.dll
    - nunit-console bin/release/smuxi-engine-tests.dll || true
    - nunit-console bin/release/smuxi-frontend-gnome-tests.dll
    - nunit-console bin/release/smuxi-frontend-stfl-tests.dll
    - chronic make clean && chronic make distcheck MCS=/usr/bin/dmcs
    - export DEB_UPSTREAM_VERSION=$(dpkg-parsechangelog -ldebian/changelog | grep ^Vers | cut -d\  -f2 | cut -d':' -f2 | sed 's,-.*,,' | sed 's,+dfsg.*,,')
    - mv smuxi-*.tar.gz ../smuxi_${DEB_UPSTREAM_VERSION}.orig.tar.gz
    - cd .. && tar -xzf smuxi_${DEB_UPSTREAM_VERSION}.orig.tar.gz
    - cd - && cp -a debian/ ../smuxi-*/
    - cd ../smuxi-* && chronic dpkg-buildpackage

notifications:
    irc:
        channels: "chat.freenode.net#smuxi-devel"
        skip_join: true
        template:
            - "%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message}"
            - "Build details : %{build_url}"
